### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by pablococeres** [tetra-framework/tetra#12] opened 2022-06-03 08:57 UTC
Hi again Sam,
I tried to replicate the todolist app and when I add it to settings I receive this error

File "~\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 966, in __init__      
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "~\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado

The file is there, what I found searching is that I have to modify shell=False to shell=True
But Im not sure where or why so maybe you know the cause.
Again something with windows I think

**Comment by samwillis** [comment] 2022-06-03 13:29
Hmm, I think it's time for me to setup and Windows VM and do some debugging, may be a few days until I'm able to get to it.

I think you may be right, from memory (it's a long time since I did anything with subprocess on Windows) there was something about setting `shell=True`...

If you want to have a go yourself the relevant lines are:

https://github.com/samwillis/tetra/blob/9d5ab31cabc563d3ad11ff8d4f591080dd7e4260/tetra/library.py#L139-L143

and:

https://github.com/samwillis/tetra/blob/9d5ab31cabc563d3ad11ff8d4f591080dd7e4260/tetra/library.py#L187-L200

Docs here: https://docs.python.org/3/library/subprocess.html#subprocess.run

**Comment by PatrickSchutte** [comment] 2022-06-04 11:11
Good morning Sam,
Thank you for your efforts, I am also having a look at this, and using your example code.
It seems like TETRA_ESBUILD_PATH has be set in the settings including the "esbuild.cmd" script file (I have just used the raw windows path in my testing).
It now goes past that step, but now I get the issue:

`G:\python\tetra\learn01\venv\Scripts\python.exe G:/python/tetra/learn01/manage.py runserver 8000
Tetra: Building Javascript and CSS
 - Libraries: lean01.default
# Building lean01.default
 - to_do_list
Watching for file changes with StatReloader
 - to_do_item
ERROR BUILDING JS: lean01.default
 - to_do_item
X [ERROR] Could not resolve "....components.py__to_do_item.js"

    lean01/__tetracache__/default/lean01_default.js:1:23:
      1 │ import to_do_item from "..\..\components.py__to_do_item.js";
        ╵                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "....components.py__to_do_item.js" as external to exclude it from the bundle, which will remove this error.

1 error
node:child_process:867
    throw err;
    ^

Error: Command failed: G:\python\tetra\learn01\node_modules\esbuild-windows-64\esbuild.exe G:\python\tetra\learn01\lean01\__tetracache__\default\lean01_default.js --bundle --minify --sourcemap --entry-names=[name]-[hash] --target=chrome80,firefox73,safari13,edge80 --outdir=G:\python\tetra\learn01\lean01\static\lean01\tetra\default --metafile=G:\python\tetra\learn01\lean01\__tetracache__\default\lean01_default.js__meta.json
    at checkExecSyncError (node:child_process:826:11)
    at Object.execFileSync (node:child_process:864:15)
    at Object.<anonymous> (G:\python\tetra\learn01\node_modules\esbuild\bin\esbuild:172:28)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 11824,
  stdout: null,
  stderr: null
}

Node.js v17.1.0
X [ERROR] Could not resolve "....\fomponents.py__to_do_item.css"

    lean01/__tetracache__/default/lean01_default.css:1:8:
      1 │ @import '..\..\components.py__to_do_item.css';
        ╵         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "....\fomponents.py__to_do_item.css" as external to exclude it from the bundle, which will remove this error.

1 error
node:child_process:867
    throw err;
    ^

Error: Command failed: G:\python\tetra\learn01\node_modules\esbuild-windows-64\esbuild.exe G:\python\tetra\learn01\lean01\__tetracache__\default\lean01_default.css --bundle --minify --sourcemap --entry-names=[name]-[hash] --loader:.png=file --loader:.svg=file --loader:.gif=file --loader:.jpg=file --loader:.jpeg=file --loader:.webm=file --loader:.woff=file --loader:.woff2=file --loader:.ttf=file --outdir=G:\python\tetra\learn01\lean01\static\lean01\tetra\default --metafile=meta.json --outbase=G:\python\tetra\learn01\lean01 --asset-names=..\..\..\../[dir]/[name] --allow-overwrite --metafile=G:\python\tetra\learn01\lean01\__tetracache__\default\lean01_default.css__meta.json
    at checkExecSyncError (node:child_process:826:11)
    at Object.execFileSync (node:child_process:864:15)
    at Object.<anonymous> (G:\python\tetra\learn01\node_modules\esbuild\bin\esbuild:172:28)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 17532,
  stdout: null,
  stderr: null
}

Node.js v17.1.0
ERROR BUILDING CSS: lean01.default
Performing system checks...

System check identified no issues (0 silenced).
June 04, 2022 - 13:08:13
Django version 4.0.5, using settings 'learn01.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
`

**Comment by samwillis** [comment] 2022-06-05 17:56
I think I have windows support working. Two things needed changing:

- esbuild needed to be executed from it's `node_modules/.bin/esbuild.cmd` variant, rather than `node_modules/.bin/esbuild`. (thanks @PatrickSchutte)

- and Tetra (on windows) was outputting windows style backslash paths for css/js import statements rather than url style forward slashes.

Both fixed and it's working for me.

If you would like to test it, you can install the version from the GitHub main branch with:
```
pip install https://github.com/samwillis/tetra/archive/refs/heads/main.zip
```

**Comment by PatrickSchutte** [comment] 2022-06-06 10:58
Thank you @samwillis , it seems to be working perfectly now.

I had to put back the full-stop in the components.py library. (from .models import ToDo) as the building/registering process fails silently, and you get a **ComponentNotFound** error.

**Comment by pablococeres** [comment] 2022-06-06 11:38
Hi Sam, I uninstall and install your the last version and the error still there.
File "C:\Users\pablo\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado

**Comment by samwillis** [comment] 2022-06-06 14:10
@PatrickSchutte Brilliant, let me know how you get on with Tetra.

@pablococeres Could you confirm you have installed esbuild and that your `node_modules` directory is in the root of the Django project? It seems odd that it's not seeing the file. May be worth trying to set the `TETRA_ESBUILD_PATH` settings to the exact path to `esbuild.cmd`.

**Comment by PatrickSchutte** [comment] 2022-06-09 08:12
> Hi Sam, I have been experimenting more with Tetra.
> 
> My structure is:
> 
>     * st
> 
>     * * components
> 
>     * * * init.py (with the double underscores but messes with the formatting)
> 
>     * * * courses.py
> 
> 
> init.py contains: `from .courses import courses`
> 
> and courses.py contains:
> 
> ```
> from tetra import Library, Component
> 
> from st.models import Learner
> 
> courses = Library()
> 
> 
> @courses.register
> class LearnerComponent(Component):
>     learner_number = ''
>     surname = ''
>     first_names = ''
>     learner: Learner
> 
>     def load(self) -> None:
>         self.learner = Learner()
> ```
> 
> If I run the below command at the console, all is built fine. `python manage.py tetrabuild`
> 
> if I however runserver, the library is added to the global libraries, but the component is not built. I assume that I'm not setting it up correctly and will re-read the multiple components section again.
> 
> Regards Patrick

Sorted, tetra  must also be before any of your apps in the settings.INSTALLED_APPS list.

**Comment by samwillis** [comment] 2022-06-13 18:57
@PatrickSchutte 

Brilliant, thanks, I will document that.

**Comment by olu-damilare** [comment] 2022-06-27 23:19
What is the correct URL to access the app? I followed the doc and built the todo app, then tried accessing it through `http://localhost:8000/tetra/` but I keep getting the 404 error. Is there something I'm missing?

**Comment by PatrickSchutte** [comment] 2022-06-28 06:57
> Hi @samwillis, please what is the correct URL to access the app? I followed the doc and built the todo app, then tried accessing it through `http://localhost:8000/tetra/` but I keep getting the 404 error. Is there something I'm missing?

Hi @olu-damilare, You would need to create an entry into your **views.py**, as well as **urls.py** so that you can render the index.html.

**Comment by olu-damilare** [comment] 2022-06-28 22:35
> > Hi @samwillis, please what is the correct URL to access the app? I followed the doc and built the todo app, then tried accessing it through `http://localhost:8000/tetra/` but I keep getting the 404 error. Is there something I'm missing?
> 
> Hi @olu-damilare, You would need to create an entry into your **views.py**, as well as **urls.py** so that you can render the index.html.

Thank you @PatrickSchutte. Just out of curiosity, is this the expected output for the todo app from the code? I'm asking because it's kind of different from what is on the webpage and I was wondering if I implemented it wrongly.
![image](https://user-images.githubusercontent.com/56642018/176315622-962e27b3-2983-4bab-a634-4189d14504ad.png)

**Comment by PatrickSchutte** [comment] 2022-06-29 06:37
> 

Excellent!, It is basically there, just the icons is missing. I assume that the code below will give you your icons.

`<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />`

**Comment by samwillis** [comment] 2022-06-29 06:53
Thanks Patrick for helping! This has highlighted I should update the walkthrough to cover those missing bits…

**Comment by olu-damilare** [comment] 2022-07-06 18:30
Hello @samwillis, I'm currently writing a blog post on how to build a full-stack app with Tetra. I've been struggling to put it together for over a week now and could really use your input and help.

**Comment by olu-damilare** [comment] 2022-07-06 18:32
@samwillis I got this error `cryptography.fernet.InvalidToken` when I tested the todo app I built again. What could be the cause? The app was working fine but suddenly began throwing this error when I clicked on the 'Add' button.

**Comment by samwillis** [comment] 2022-07-06 20:23
Hi @olu-damilare,

Thats an interesting one, could you send me your code. That can happen if you cleared your cache, deleted your session cookie, changed the Django SECRET_KEY or the users session what ended for any other reason. Had anything else changed in the environment or code?

**Comment by olu-damilare** [comment] 2022-07-08 09:59
@samwillis How does Tetra handle file upload? The django server is not receiving the file from the Tetra component. Also, the doc does not contain any use case or walk through as to how to go about this.

**Comment by nerdoc** [comment] 2024-04-09 22:30
As there are plenty of different questions here in the thread, not related to the "Windows support", and the OP's issue seems to be solved, I think we can close this issue here.
@olu-damilare - file upload seems to be an issue still, would you like to file a separate issue for that?

**Closed by nerdoc** 2024-04-09 22:30 UTC
