### ISSUE TITLE
Changing the contents of a template file referenced with template_name = doesn't rebuild the component

### ISSUE THREAD

**Issue by gsxdsm** [tetra-framework/tetra#73] opened 2024-10-23 01:26 UTC
When I change the template that is in a separate file (referenced by template_name in the component), the overall component doesn't reload. Have to restart the server (or change the .py component) to trigger a refresh.

**Comment by nerdoc** [comment] 2024-10-26 18:21
As the discussion is already completely there, I'll mark this one as duplicate of #74.
(issues were opened almoust sumultaneously, 4h diff :laughing:)

**Closed by nerdoc** 2024-10-26 18:21 UTC
